<?php

    $region_data = "INSERT INTO `regions`(`nom`)
VALUES 
('ADAMAOUA'),
('CENTRE'),
('EST'),
('EXTREME NORD'),
('LITTORAL'),
('NORD'),
('NORD OUEST'),
('OUEST'),
('SUD'),
('SUD-OUEST')";


$departement_data = "INSERT INTO `departements`(`id_region`, `nom`) 
VALUES 
(1,'DJEREM'),
(1,'FARO ET DEO'),
(1,'MAYO BANYO'),
(1,'MBERE'),
(1,'VINA'),
(2,'HAUTE-SANAGA'),
(2,'LEKIE'),
(2,'MBAM ET INOUBOU'),
(2,'MBAM ET KIM'),
(2,'MEFOU ET AFAMBA'),
(2,'MEFOU ET AKONO'),
(2,'MFOUNDI'),
(2,'NYONG ET KELLE'),
(2,'NYONG ET MFOUMOU'),
(2,'NYONG ET SO\'O'),
(3,'BOUMBA ET NGOKO'),
(3,'HAUT NYONG'),
(3,'KADEY'),
(3,'LOM ET DJEREM'),
(4,'DIAMARE'),
(4,'LOGONE ET CHARI'),
(4,'MAYO DANAY'),
(4,'MAYO KANI'),
(4,'MAYO SAVA'),
(4,'MAYO TSANAGA'),
(5,'MOUNGO'),
(5,'NKAM'),
(5,'SANAGA MARITIME'),
(5,'WOURI'),
(6,'BENOUE'),
(6,'FARO'),
(6,'MAYO LOUTI'),
(6,'MAYO REY'),

(7,'BUI'),
(7,'BOYO'),
(7,'DONGA-MANTUNG'),
(7,'MENCHUM'),
(7,'MEZAM'),
(7,'MOMO'),
(7,'NGO-KENTUNJIA'),

(8,'BAMBOUTOS'),
(8,'HAUT NKAM'),
(8,'HAUTS PLATEAUX'),
(8,'KOUNG KHI'),
(8,'MENOUA'),
(8,'MIFI'),
(8,'NDE'),
(8,'NOUN'),

(9,'DJA ET LOBO'),
(9,'VALLEE DU NTEM'),
(9,'MVILA'),
(9,'OCEAN'),

(10,'FAKO'),
(10,'KUPE MANENGUBA'),
(10,'LEBIALEM'),
(10,'MANYU'),
(10,'MEME'),
(10,'NDIAN')";

$arrondissement_data = "
INSERT INTO `arrondissements`(`id_departement`, `nom`) VALUES 
(1,'NGAOUNDAL'),
(1,'TIBATI'),

(2,'MAYO-BALEO'),
(2,'TIGNERE'),
(2,'GALIM-TIGNERE'),
(2,'KONTCHA'),

(3,'BANYO'),
(3,'BANKIM'),
(3,'MAYO-DARLE'),

(4,'MEIGANGA'),
(4,'DJOHONG'),
(4,'DIR'),
(4,'NGAOUI'),

(5,'NGAOUNDERE 1er'),
(5,'NGAOUNDERE 2e'),
(5,'NGAOUNDERE 3e'),
(5,'BELEL'),
(5,'MBE'),
(5,'NGANHA'),
(5,'NYAMBAKA'),
(5,'MARTAP'),

(6,'MBANDJOCK'),
(6,'MINTA'),
(6,'NANGA-EBOKO'),
(6,'NKOTENG'),
(6,'BIBEY'),
(6,'NSEM'),
(6,'LEMBE-YEZOUM'),

(7,'EVODOULA'),
(7,'MONATELE'),
(7,'OBALA'),
(7,'OKOLA'),
(7,'SA\'A'),
(7,'ELIG-MFOMO'),
(7,'EBEBDA'),
(7,'BATSCHENGA'),
(7,'LOBO'),

(8,'BAFIA'),
(8,'BOKITO'),
(8,'DEUK'),
(8,'MAKENENE'),
(8,'NDIKINIMEKI'),
(8,'OMBESSA'),
(8,'KIIKI'),
(8,'KON-YAMBETTA'),

(9,'NTUI'),
(9,'NGAMBE-TIKAR'),
(9,'NGORO'),
(9,'YOKO'),
(9,'MBANGASSINA'),

(10,'MFOU'),
(10,'ESSE'),
(10,'AWAE'),
(10,'SOA'),
(10,'AFANLOUM'),
(10,'OLANGUINA'),
(10,'EDZENDOUAN'),
(10,'NKOLAFAMBA'),

(11,'NGOUMOU'),
(11,'AKONO'),
(11,'MBANKOMO'),
(11,'BIKOK'),

(12,'YAOUNDE I'),
(12,'YAOUNDE II'),
(12,'YAOUNDE III'),
(12,'YAOUNDE IV'),
(12,'YAOUNDE V'),
(12,'YAOUNDE VI'),
(12,'YAOUNDE VII'),

(13, 'BOT-MAKAK') ,
(13, 'ESEKA') ,
(13, 'MAKAK') ,
(13, 'MESSONDO') ,
(13, 'NGOG-MAPUBI') ,
(13, 'MATOMB') ,
(13, 'DIBANG') ,
(13, 'NGUIBASSAL') ,
(13, 'BONDJOCK') ,
(13, 'BIYOUHA') ,

(14, 'AKONOLINGA') ,
(14, 'AYOS') ,
(14, 'ENDOM') ,
(14, 'MENGANG') ,
(14, 'KOBDOMBO'),

(15, 'DZENG') ,
(15, 'MBALMAYO') ,
(15, 'NGOMEDZAP') ,
(15, 'AKOEMAN') ,
(15, 'MENGUEME') ,
(15, 'NKOL-METET') ,

(16, 'MOLOUNDOU') ,
(16, 'SALAPOUMBE') ,
(16, 'GARI-GOMBO') ,
(16, 'YOKADOUMAT') ,

(17, 'ABONG-MBANG') ,
(17, 'DOUME') ,
(17, 'LOMIE') ,
(17, 'MESSAMENA') ,
(17, 'NGUELEMENDOUKA') ,
(17, 'DIMAKO') ,
(17, 'NGOYLA') ,
(17, 'ATOK') ,
(17, 'ANGOSSAS') ,
(17, 'DJA') ,
(17, 'DOUMAINTANG') ,
(17, 'MESSOK') ,
(17, 'SAMALOMO') ,
(17, 'MBOMA') ,


(18, 'BATOURI') ,
(18, 'NDELELE') ,
(18, 'KETTE') ,
(18, 'MBANG') ,
(18, 'NDEM-NAM') ,
(18, 'BOMBE') ,
(18, 'MBOTORO'),

(19, '1er BERTOUA 1er') ,
(19, '2e BERTOUA 2e') ,
(19, 'BETARE-OYA') ,
(19, 'BELABO') ,
(19, 'GAROUA-BOULAÏ') ,
(19, 'DIANG') ,
(19, 'MANDJOU') ,
(19, 'NGOURA') ,

(20, 'BOGO') ,
(20, '1er MAROUA 1er') ,
(20, '2e MAROUA 2ème') ,
(20, '3e MAROUA 3ème') ,
(20, 'MERI') ,
(20, 'GAZAWA') ,
(20, 'PETTE') ,
(20, 'DARGALA') ,
(20, 'NDOUKOULA ') ,

(21, 'KOUSSERI') ,
(21, 'MAKARY') ,
(21, 'LOGONE-BIRNI') ,
(21, 'GOULFEY') ,
(21, 'WAZA') ,
(21, 'FOTOKOL') ,
(21, 'HILE-HALIFA') ,
(21, 'BLANGOUA') ,
(21, 'DARAK') ,
(21, 'ZINA') ,

(22, 'KAR-HAY') ,
(22, 'DATCHEKA') ,
(22, 'YAGOUA') ,
(22, 'GUERE') ,
(22, 'MAGA') ,
(22, 'KALFOU') ,
(22, 'WINA') ,
(22, 'GUEME') ,
(22, 'TCHATIBALI') ,
(22, 'GOBO') ,
(22, 'KAI-KAI') ,

(23, 'KAELE') ,
(23, 'GUIDIGUIS') ,
(23, 'MINDIF') ,
(23, 'MOUTOURWA') ,
(23, 'MOULVOUDAYE') ,
(23, 'PORHI') ,
(23, 'TAIBONG') ,

(24, 'MORA') ,
(24, 'TOKOMBERE') ,
(24, 'KOLOFATA') ,

(25, 'MOKOLO') ,
(25, 'BOURRHA') ,
(25, 'KOZA') ,
(25, 'HINA') ,
(25, 'MOGODE') ,
(25, 'MAYO-MOSKOTA') ,
(25, 'SOULEDE-ROUA') ,

(26, 'DIBOMBARI') ,
(26, 'LOUM') ,
(26, 'MANJO') ,
(26, 'MBANGA') ,
(26, 'MELONG') ,
(26, '1er NKONGSAMBA 1er') ,
(26, '2e NKONGSAMBA 2e') ,
(26, '3e NKONGSAMBA 3e') ,
(26, 'EBONE') ,
(26, 'BARE-BAKEM') ,
(26, 'PENJA') ,
(26, 'BONALEA') ,
(26, 'MOMBO') ,

(27, 'NKONDJOCK') ,
(27, 'YABASSI') ,
(27, 'YINGUI') ,
(27, 'NORD-MAKOMBE ') ,

(28, 'DIZANGUE') ,
(28, 'EDEA 1er') ,
(28, 'EDEA 2ème') ,
(28, 'NDOM') ,
(28, 'NGAMBE') ,
(28, 'POUMA') ,
(28, 'MOUANKO') ,
(28, 'DIBAMBA') ,
(28, 'NGWEI') ,
(28, 'NYANON') ,
(28, 'MASSOCK-SONGLOULOU') ,

(29, 'DOUALA 1er') ,
(29, 'DOUALA 2e') ,
(29, 'DOUALA 3e') ,
(29, 'DOUALA 4e') ,
(29, 'DOUALA 5e') ,
(29, 'MANOKA') ,

(30, 'GAROUA 1er') ,
(30, 'GAROUA 2e') ,
(30, 'GAROUA 3e') ,
(30, 'BIBEMI') ,
(30, 'PITOA') ,
(30, 'LAGDO') ,
(30, 'DEMBO') ,
(30, 'NGONG') ,
(30, 'HOURNA BARDANKE') ,
(30, 'TOUROUA') ,
(30, 'BASCHEO') ,
(30, 'DEMSA') ,

(31, 'POLI') ,
(31, 'BEKA') ,

(32, 'GUIDER') ,
(32, 'MAYO-OULO') ,
(32, 'FIGUIL') ,

(33, 'REY-BOUBA') ,
(33, 'TCHOLLIRE') ,
(33, 'TOUBORO') ,
(33, 'MADINGRING') ,

(34, 'JAKIRI') ,
(34, 'KUMBO') ,
(34, 'ELAK-OKU') ,
(34, 'MBIAME') ,
(34, 'EKOR') ,
(34, 'NKUM') ,

(35, 'FUNDONG  ') ,
(35, 'BELO') ,
(35, 'BUM') ,
(35, 'NJINIKOM'),

(36, 'NKAMBE') ,
(36, 'NWA') ,
(36, 'AKO') ,
(36, 'MISAJE') ,
(36, 'NDU') ,

(37, 'WUM') ,
(37, 'FURU-AWA') ,
(37, 'VALLEY BENAKUMA') ,
(37, 'ZHOA') ,

(38, '1er BAMENDA1er') ,
(38, '2e BAMENDA 2e') ,
(38, '3e BAMENDA 3e') ,
(38, 'BALI') ,
(38, 'TUBAH') ,
(38, 'BAFUT') ,
(38, 'SANTA') ,

(39, 'BATIBO') ,
(39, 'MBENGWI') ,
(39, 'NJIKWA') ,
(39, 'ANDEK') ,
(39, 'WIDIKUM-BOFFE') ,

(40, 'NDOP') ,
(40, 'BABESSI') ,
(40, 'BALIKUMBAT') ,

(41, 'MBOUDA') ,
(41, 'GALIM') ,
(41, 'BATCHAM') ,
(41, 'BABADJOU'),

(42, 'BAFANG') ,
(42, 'BANA') ,
(42, 'BANDJA') ,
(42, 'KEKEM') ,
(42, 'BAKOU') ,
(42, 'BANKA') ,
(42, 'BANWA') ,

(43, 'BAHAM') ,
(43, 'BAMENDJOU') ,
(43, 'BANGOU') ,
(43, 'BATIE') ,

(44, 'PETTE-BANDJOUN') ,
(44, 'BAYANGAM ') ,
(44, 'DJEBEM') ,

(45, 'DSCHANG') ,
(45, 'PENKA-MICHEl') ,
(45, 'FOKOUE') ,
(45, 'NKONG-ZEM') ,
(45, 'SANTCHOU') ,
(45, 'FONGO TONGO') ,

(46, 'BAFOUSSAM 1er') ,
(46, 'BAFOUSSAM 2e') ,
(46, 'BAFOUSSAM 3e') ,

(47, 'BANGANGTE ') ,
(47, 'BAZOU') ,
(47, 'TONGA') ,
(47, 'BASSAMBA') ,

(48, 'FOUMBAN') ,
(48, 'FOUMBOT') ,
(48, 'MALENTOUEN') ,
(48, 'MASSANGAM') ,
(48, 'MAGBA') ,
(48, 'KOUTABA') ,
(48, 'KOUOPTAMO') ,
(48, 'NJIMON') ,

(49, 'BENGBIS') ,
(49, 'DJOUM') ,
(49, 'SANGMELIMA') ,
(49, 'ZOETELE') ,
(49, 'OVENG') ,
(49, 'MINTOM ') ,
(49, 'MEYOMESSALA') ,
(49, 'MEYOMESSI') ,
(50, 'AMBAM') ,
(50, 'MA\'AN') ,
(50, 'OLAMZE') ,
(50, 'KYE OSSI') ,

(51, 'EBOLOWA 1er') ,
(51, 'EBOLOWA 2e') ,
(51, 'BIWONG-BANE') ,
(51, 'MVANGAN') ,
(51, 'MENGONG') ,
(51, 'NGOULEMAKONG') ,
(51, 'EFOULAN') ,
(51, 'BIWONG BULU') ,

(53, 'AKOM II') ,
(53, 'CAMPO') ,
(53, 'KRIBI 1er') ,
(53, 'KRIBI 2e') ,
(53, 'LOLODORF') ,
(53, 'MVENGUE') ,
(53, 'BIPINDI') ,
(53, 'LOKOUNDJE') ,
(53, 'NIETE'),

(54, 'MUYUKA') ,
(54, 'TIKO') ,
(54, 'LIMBE 1er') ,
(54, 'LIMBE 2e') ,
(54, 'LIMBE 3e') ,
(54, 'BUEA') ,
(54, 'IDENAU'),

(55, 'BANGEM') ,
(55, 'NGUTI') ,
(55, 'TOMBEL'),

(56, 'MENJI') ,
(56, 'ALOU') ,
(56, 'WABANE'),

(57, 'AKWAYA') ,
(57, 'MAMFE') ,
(57, 'EYUMODJOCK') ,
(57, 'TINTO') ,

(58, 'KUMBA 1er') ,
(58, 'KUMBA 2e') ,
(58, 'KUMBA 3e') ,
(58, 'KONYE') ,
(58, 'BONGE') ,

(59, 'BAMUSSO') ,
(59, 'EKONDO-TITI ') ,
(59, 'ISANGUELE') ,
(59, 'MUNDEMBA') ,
(59, 'KOMBO ABEDIMO') ,
(59, 'KOMBO IDINTI') ,
(59, 'IDABATO') ,
(59, 'DIKOME-BALUE') ,
(59, 'TOKO')";



$tables_data[] =  $region_data;
$tables_data[] = $departement_data;
$tables_data[] = $arrondissement_data;